name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output github 'context data' (meta info)
        id: github_context_step
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github)}}
